apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: spring-k8s
          image: spring-k8s:latest
          env:
            - name: DUMMY
              value: 'dummy'
            #- name: SPRING_CLOUD_BOOTSTRAP_ENABLED
            #  value: "true"
            #- name: SPRING_CONFIG_IMPORT
            #  value: "kubernetes:"
          ports:
            - containerPort: 8080
          imagePullPolicy: Never